apiVersion: helm.toolkit.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: weatherapp-auth
  namespace: apps
spec:
  chart:
    spec:
      version: "0.1.0"
  valuesFrom:
    - kind: Secret
      name: auth
    # mysql:
    #   auth:
    #     username: authuserproduction
    #     password: authpasswordproduction
    #     database: weatherapproduction
    #     createDatabase: true
