---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  address: https://hooks.slack.com/services/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
  channel: general
  secretRef:
    name: slack-secret
  type: slack
